apply plugin: 'java-library'

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
java.sourceCompatibility = java.targetCompatibility = appJavaCompatibility

test {
    workingDir file('src/main/assets')
    testLogging {
        events 'passed', 'failed'
        exceptionFormat 'full'
        showStandardStreams = true
    }
}

dependencies {
    api project(':SPD-classes')
    implementation project(':services')
    testImplementation 'junit:junit:4.13.2'
    testImplementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
    testRuntimeOnly "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}
